name: sync a fork
on:
    repository_dispatch:
        types: run-sync
    schedule:
        - cron: "1 * * * *"

jobs:
    sync-fork:
        runs-on: ubuntu-latest
        steps:
            - name: clone cache
              uses: actions/cache@v3
              with:
                  path: .cloneDir-source
                  key: cache-phpmyadmin
            - name: sync phpmyadmin fork
              uses: sudo-bot/action-fork-sync@v1.0.4
              with:
                  source-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/phpmyadmin/phpmyadmin.git"
                  fork-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/williamdes/phpmyadmintest.git"
                  clone-depth: "1000"
                  branches: "master,QA_5_2,QA_5_1,QA_5_0,QA_4_9,STABLE"
